# General Jekyll Config
url: https://csexton.com
safe: true
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
kramdown:
  input: GFM
  hard_wrap: false
poole:
  default_layout: post
plugins:
  - jekyll-redirect-from
excerpt_separator: <!--more-->
